### ISSUE TITLE
Bien mais une partie pratique?

### ISSUE THREAD

**Issue by borrougagnou** [bpesquet/poo-csharp#7]
J'ai bien aimé ce livre et étant de Bordeaux, voir un livre comme cela fais du bien, le seul hic que j'ai, c'est le manque de pratique :/ d'où le fais que c'est bien, j'ai appris, mais maintenant le problème c'est: "retenir" x) et je t'avoue que je n'ai pas pu bien retenir d'un jour à l'autre :/

La programmation objet c'est chaud quand on a fais que du C .-.

Voila voila

**Comment by bpesquet** [comment]
Bonjour,
Ce livre est uniquement un support de cours. Il faut effectivement réaliser des exercices pour véritablement comprendre la POO. A ce jour, les miens ne sont pas publiés, mais il en existe de nombreux en ligne ("exercice poo" sur Google).
Bonne continuation.
